# Generated by Django 5.0.6 on 2024-06-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0003_alter_members_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
